version: '3.8'

services:
  mongo:
    container_name: blogdb
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: blog
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    networks:
      - local  

  app:
    depends_on:
      - mongo
    container_name: blog-api   
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/app      
    ports:
      - "3000:3000"
    networks:
      - local  

networks:
  local:
    name: local